query queryWithVariables(
  $nonnullableScalar: String!,
  $nullableScalar: String,
  $nonnullableNonnullableScalars: [String!]!,
  $nullableNullableScalars: [String],
  $nonnullableNonnullableNonnullableScalars: [[String!]!]!,
  $nullableNullableNullableScalars: [[String]],
) {
  queryWithVariables(
    nonnullableScalar: $nonnullableScalar,
    nullableScalar: $nullableScalar,
    nonnullableNonnullableScalars: $nonnullableNonnullableScalars,
    nullableNullableScalars: $nullableNullableScalars,
    nonnullableNonnullableNonnullableScalars: $nonnullableNonnullableNonnullableScalars,
    nullableNullableNullableScalars: $nullableNullableNullableScalars,
  )
}